### ISSUE TITLE
ng build BUILD ERROR Can't export value as it was neither declared nor imported

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/songhay-ng-workspace#1]
this error is described here: https://stackoverflow.com/questions/44133513/cant-export-service-from-module-it-was-neither-declared-nor-imported

full error:
```console
ng build @songhay/core
Building Angular Package
Building entry point '@songhay/core'
Compiling TypeScript sources through ngc

BUILD ERROR
: Can't export value AppDataService in ../songhay-ng-workspace/songhay/projects/songhay/core/src/lib/services/songhay-app-data.service.ts from SonghayAngularCoreModule in ../songhay-ng-workspace/songhay/projects/songhay/core/src/lib/songhay-angular-core.module.ts as it was neither declared nor imported!
: Can't export value DomSanitizerUtility in ../songhay-ng-workspace/songhay/projects/songhay/core/src/lib/services/songhay-dom-sanitizer.utility.ts from SonghayAngularCoreModule in ../songhay-ng-workspace/songhay/projects/songhay/core/src/lib/songhay-angular-core.module.ts as it was neither declared nor imported!

Error: : Can't export value AppDataService in ../songhay-ng-workspace/songhay/projects/songhay/core/src/lib/services/songhay-app-data.service.ts from SonghayAngularCoreModule in ../songhay-ng-workspace/songhay/projects/songhay/core/src/lib/songhay-angular-core.module.ts as it was neither declared nor imported!
: Can't export value DomSanitizerUtility in ../songhay-ng-workspace/songhay/projects/songhay/core/src/lib/services/songhay-dom-sanitizer.utility.ts from SonghayAngularCoreModule in ../songhay-ng-workspace/songhay/projects/songhay/core/src/lib/songhay-angular-core.module.ts as it was neither declared nor imported!

    at Object.<anonymous> (..\songhay-ng-workspace\songhay\node_modules\ng-packagr\lib\ngc\compile-source-files.js:51:19)
    at Generator.next (<anonymous>)
    at fulfilled (..\songhay-ng-workspace\songhay\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)

: Can't export value AppDataService in ../songhay-ng-workspace/songhay/projects/songhay/core/src/lib/services/songhay-app-data.service.ts from SonghayAngularCoreModule in ../songhay-ng-workspace/songhay/projects/songhay/core/src/lib/songhay-angular-core.module.ts as it was neither declared nor imported!
: Can't export value DomSanitizerUtility in ../songhay-ng-workspace/songhay/projects/songhay/core/src/lib/services/songhay-dom-sanitizer.utility.ts from SonghayAngularCoreModule in ../songhay-ng-workspace/songhay/projects/songhay/core/src/lib/songhay-angular-core.module.ts as it was neither declared nor imported!

Error: : Can't export value AppDataService in ../songhay-ng-workspace/songhay/projects/songhay/core/src/lib/services/songhay-app-data.service.ts from SonghayAngularCoreModule in ../songhay-ng-workspace/songhay/projects/songhay/core/src/lib/songhay-angular-core.module.ts as it was neither declared nor imported!
: Can't export value DomSanitizerUtility in ../songhay-ng-workspace/songhay/projects/songhay/core/src/lib/services/songhay-dom-sanitizer.utility.ts from SonghayAngularCoreModule in ../songhay-ng-workspace/songhay/projects/songhay/core/src/lib/songhay-angular-core.module.ts as it was neither declared nor imported!

    at Object.<anonymous> (..\songhay-ng-workspace\songhay\node_modules\ng-packagr\lib\ngc\compile-source-files.js:51:19)
    at Generator.next (<anonymous>)
    at fulfilled (..\songhay-ng-workspace\songhay\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)
```

**Comment by BryanWilhite** [comment]
both `AppDataService` and `DomSanitizerUtility` are services and, according to [this StackOverflow answer](https://stackoverflow.com/a/44133569/22944), services are not supposed to be in module `exports`
