### ISSUE TITLE
Error: Cannot call a namespace ('moment')

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/songhay-ng-workspace#2]
```console
ng build @songhay/player-video-you-tube
Building Angular Package
Building entry point '@songhay/player-video-you-tube'
Compiling TypeScript sources through ngc
Bundling to FESM2015

BUILD ERROR
Cannot call a namespace ('moment')
Error: Cannot call a namespace ('moment')
    at error (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:3460:30)
    at Module.error (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:13349:9)
    at CallExpression.bind (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:10228:30)
    at MemberExpression$$1.NodeBase.bind (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:9183:23)
    at MemberExpression$$1.bind (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:11261:35)
    at CallExpression.NodeBase.bind (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:9183:23)
    at CallExpression.bind (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:10224:31)
    at VariableDeclarator.NodeBase.bind (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:9183:23)
    at VariableDeclaration$$1.NodeBase.bind (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:9179:31)
    at BlockStatement$$1.NodeBase.bind (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:9179:31)

Cannot call a namespace ('moment')
Error: Cannot call a namespace ('moment')
    at error (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:3460:30)
    at Module.error (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:13349:9)
    at CallExpression.bind (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:10228:30)
    at MemberExpression$$1.NodeBase.bind (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:9183:23)
    at MemberExpression$$1.bind (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:11261:35)
    at CallExpression.NodeBase.bind (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:9183:23)
    at CallExpression.bind (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:10224:31)
    at VariableDeclarator.NodeBase.bind (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:9183:23)
    at VariableDeclaration$$1.NodeBase.bind (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:9179:31)
    at BlockStatement$$1.NodeBase.bind (..\songhay-ng-workspace\songhay\node_modules\rollup\dist\rollup.js:9179:31)
```

**Comment by BryanWilhite** [comment]
workaround: https://github.com/jvandemo/generator-angular2-library/issues/221#issuecomment-355945207
