### ISSUE TITLE
clicking on yt dash link throws error

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/songhay-ng-workspace#5]
the Dashboard [project](https://github.com/BryanWilhite/Songhay.Dashboard) hosting `@songhay/player-video-you-tube` lib is throwing an error when deep-linking into lib:

```console
ERROR Error: Uncaught (in promise): TypeError: Array.prototype.map: argument is not a Function object TypeError: Array.prototype.map: argument is not a Function object at webpackAsyncContext (http://localhost:4200/main.js:345:2) at SystemJsNgModuleLoader.prototype.loadAndCompile (http://localhost:4200/vendor.js:83114:9) at SystemJsNgModuleLoader.prototype.load (http://localhost:4200/vendor.js:83106:9) at RouterConfigLoader.prototype.loadModuleFactory (http://localhost:4200/vendor.js:153224:13) at RouterConfigLoader.prototype.load (http://localhost:4200/vendor.js:153212:9) at Anonymous function (http://localhost:4200/vendor.js:152215:21) at MergeMapSubscriber.prototype._tryNext (http://localhost:4200/vendor.js:199943:13) at MergeMapSubscriber.prototype._next (http://localhost:4200/vendor.js:199933:13) at Subscriber.prototype.next (http://localhost:4200/vendor.js:194390:13) at Anonymous function (http://localhost:4200/vendor.js:196569:9)
```

**Comment by BryanWilhite** [comment]
a hosting app should be set up in the workspace to attempt to replicate the problem:

```console
ng generate application --routing=true --style=scss --dry-run=true
```

**Comment by BryanWilhite** [comment]
adding `yt` component:

```console
ng g component components/yt --flat=false --module=app  --project client --style=scss --dry-run=true
```

**Comment by BryanWilhite** [comment]
deep-linking into lib works from `client`:

![image](https://user-images.githubusercontent.com/5226627/53603342-12d28400-3b66-11e9-9f18-1132ac13dd10.png)

**Comment by BryanWilhite** [comment]
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```

![alt](data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==)

**Comment by BryanWilhite** [comment]
![][image_ref_a32ff4ads]

More text here...
...

[image_ref_a32ff4ads]: data:image/png;base64,iVBORw0KGgoAAAANSUhEke02C1MyA29UWKgPA...RS12D==

**Comment by BryanWilhite** [comment]
@epelc shows us (in video form) that route modules in a library are kind of useless; instead we see that route _information_ should come from the library:

![image](https://user-images.githubusercontent.com/5226627/53662541-fa22a680-3c17-11e9-92c1-4b5c573d141a.png)
